### ISSUE TITLE
cmd/cue: trim default + optional interaction

### ISSUE THREAD

**Issue by vikstrous2** [cuelang/cue#759] opened 2021-02-11 14:41 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version v0.3.0-beta.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?
`tmp.cue`
```
#maybeString: {ip?: string}
something: ip: *"default" | string
something: #maybeString
```
```
cue trim tmp.cue
```

### What did you expect to see?
I don't think this looks like something that can be trimmed, so probably no change.

### What did you see instead?
```
  {
      #maybeString: close({
        ip?: string
      })
      something: {
-         ip: (*"default" | string) & string
+         ip?: string
      }
  }
Aborting trim, output differs after trimming. This is a bug! Use -i to force trim.
You can file a bug here: https://github.com/cuelang/cue/issues/new?assignees=&labels=NeedsInvestigation&template=bug_report.md&title=
```

**Comment by myitcv** [comment] 2021-02-12 15:43
Confirmed with 760aa11:

```
cp main.cue.golden main.cue
exec cue trim ./...
cmp main.cue main.cue.golden

-- main.cue.golden --
package main

#maybeString: {ip?: string}
something: ip: *"default" | string
something: #maybeString
```

Marking as a feature request because `trim` needs to be coded for each case.

**Closed** 2021-02-13 17:41 UTC
Labels: NeedsFix, trim

**Comment by cueckoo** [comment] 2021-07-03 13:03
This issue has been migrated to https://github.com/cue-lang/cue/issues/759.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
