### ISSUE TITLE
cmd/cue: trim bug with builtin default

### ISSUE THREAD

**Issue by vikstrous2** [cuelang/cue#760] opened 2021-02-11 15:15 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version v0.3.0-beta.4 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?
```
package kube

import "strings"

service: [ID=_]: {
	_service_name: *strings.TrimSuffix(ID, "-suffix") | string
}
service: "a-suffix": _shared
service: "b-suffix": _shared
_shared: {
	_service_name: "a"
}
```
```
cue trim ./...
```

### What did you expect to see?
no trimming

### What did you see instead?
```
  {
      service: {
        {
                [ID=_]: {
                        _service_name: *strings.TrimSuffix(ID, "-suffix") | string
                }
        }
        "a-suffix": _shared
        "b-suffix": _shared
      }
      _shared: {
-         _service_name: "a"
      }
  }
Aborting trim, output differs after trimming. This is a bug! Use -i to force trim.
You can file a bug here: https://github.com/cuelang/cue/issues/new?assignees=&labels=NeedsInvestigation&template=bug_report.md&title=
```

**Comment by myitcv** [comment] 2021-02-12 15:36
Confirmed with 760aa115.

**Comment by myitcv** [comment] 2021-02-12 15:37
Marking this as a feature request, because every aspect of trim needs to be implemented separately.

**Comment by mpvl** [comment] 2021-02-12 20:29
But it's a bug if it produces incorrect results. So switching to bug.

**Comment by myitcv** [comment] 2021-02-12 20:48
Ah thanks for clarifying.

**Closed** 2021-02-13 17:41 UTC
Labels: NeedsFix, trim

**Comment by cueckoo** [comment] 2021-07-03 13:03
This issue has been migrated to https://github.com/cue-lang/cue/issues/760.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
