### ISSUE TITLE
cmd/cue: unclear how to validate selector and qualified identifier errors in disjunctions

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#629] opened 2021-01-07 14:36 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +40d9da31-dirty linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Consider the following:

```
-- cue.mod/module.cue --
module: "mod.com"
-- fn/fn.cue --
package fn
-- x.cue --
package x

import "mod.com/fn"

s: {}

a: 5 | y    // ERROR: reference "y" not found
b: 5 | s.y  // not an error
c: 5 | fn.y // not an error
```

`cue eval` gives the following:

```
a: reference "y" not found:
    ./x.cue:7:8
```

The error above is as expected. 

According to my reading of the spec, both `s.y` and `fn.y` evaluate to `_|_`. Hence, strictly speaking, the output above is correct.

But the lack of errors for lines 8 and 9 are tricky as the author of this code. My error has been masked by the use of a disjunction. 

Note: this repro is derived from a real-world example where this typo was made across tens of files. 

### What did you expect to see?

Unclear, because it's conceivable that a different user might have intended the above behaviour, and so not expect to see errors for `s.y` or `fn.y`

cc @jlongtine

**Comment by mpvl** [comment] 2021-01-12 21:11
Like with Go, one should distinguish a reference from a selector.

A missing reference, the first `y` in this case, is a unrecoverable compile-time error. It is illegal CUE. CUE cannot evaluate meaningfully without resolving a reference.

This is the only reference of `y`. The other `y`'s are selectors in the resolved references `fn` and `s`. These are not compile time errors. As per the CUE spec, these are just errors that get eliminated as disjuncts as part of CUE evaluation and thus will not generate user-facing errors. In fact, these errors are even resolvable (it is an "incomplete" error), as a user may resolve the error by making a configuration more concrete.

In the case of the package one could argue the user has no control over adding more values and thus the error should be terminal, but also terminal evaluation errors simply get eliminated as a disjunct.

I'm not sure what errors you would want to present to the user in this case, as these really aren't errors. A linter could maybe complain about the package reference, assuming that packages are static. But the `s.y` expression is completely valid and could be as intended. It would be incorrect for a linter to complain about this. 

A different story would be if `s` were closed. In that case `s.y` could never resolve to a valid value, which would indeed be suspicious. So in that case it makes sense for a linter to complain, even though it is still valid CUE. We could also consider making this not valid CUE, although the definition of that would be somewhat tricky.

**Comment by myitcv** [comment] 2021-01-13 05:54
> Like with Go, one should distinguish a reference from a selector.

Indeed, which is why I included all three, as a compare and contrast. The case of a bad reference is I agree clear.

> In the case of the package one could argue the user has no control over adding more values and thus the error should be terminal, but also terminal evaluation errors simply get eliminated as a disjunct.

Yes, the case of a package selector is what gave rise to this case. 

> A different story would be if `s` were closed. In that case `s.y` could never resolve to a valid value, which would indeed be suspicious. So in that case it makes sense for a linter to complain, even though it is still valid CUE. We could also consider making this not valid CUE, although the definition of that would be somewhat tricky.

You're quite right, I intended for my example using `s` to either be a definition or `close()`-d. Because as written it it not contentious at all. Here's an updated version:

```
exec cue eval
-- cue.mod/module.cue --
module: "mod.com"
-- fn/fn.cue --
package fn
-- x.cue --
package x

import "mod.com/fn"

s: {}
#def: {}

a: 5 | y        // ERROR: reference "y" not found
b: 5 | s.y      // not an error - OK
c: 5 | fn.y     // not an error - ??
d: 5 | #def.y   // not an error - ??
```

> So in that case it makes sense for a linter to complain, even though it is still valid CUE. We could also consider making this not valid CUE, although the definition of that would be somewhat tricky.

In the case of the package and definition selectors (cases `c` and `d` above), I can see how it being something a linter would catch might indeed make sense (given as you say it is valid CUE).

**Comment by mpvl** [comment] 2021-01-13 08:57
> I can see how it being something a linter would catch might indeed make sense (given as you say it is valid CUE).

It probably makes sense to do something very similar to what Go does, and automatically trigger such errors for `cue test` and `cue vet`, for instance.

**Comment by mpvl** [comment] 2021-01-13 09:07
FTR: internally, CUE marks `s.y` as an `incomplete` error (could be resolved by making a configuration more concrete) and `#def.y` as an `eval` error (cannot be fixed by making something more concrete). So there is a mechanism in place to distinguish these cases already.

For `fn.y` we would need to decide. Technically, as the top-level of the package isn't closed, `fn.y` could still be resolved by making the package more concrete. One could argue that this is not going to happen. It is very hard to figure out what would be the right semantics in the general case: as values of packages and non-packages get mixed during computation, things get complicated. So I would argue this still should be marked as an `incomplete` error during evaluation. However, a linter could still recognize this as a special case (incomplete error of an unknown selector into a package reference) and complain.

**Comment by myitcv** [comment] 2021-05-26 15:26
@mpvl I suggest we at least consider this for `v0.5.0` - thoughts?

**Comment by cueckoo** [comment] 2021-07-03 13:01
This issue has been migrated to https://github.com/cue-lang/cue/issues/629.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.

**Closed by cueckoo** 2021-07-03 13:01 UTC
Labels: NeedsInvestigation
