### ISSUE TITLE
cue: ResolveReferences option not work in method "Syntax" 

### ISSUE THREAD

**Issue by leejanee** [cuelang/cue#867] opened 2021-04-01 11:38 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.3.0-beta.8
</pre>

### What did you do?

The code is as follows
```
       var src =`
t: {name: string}
output: [...t]
`
	var r cue.Runtime
	inst,_:=r.Compile("-",src)
	ct,_:=format.Node(inst.Value().Lookup("output").Syntax(cue.ResolveReferences(true)))
	fmt.Println(string(ct))
```
After running the code,I get 
```
[...t]
```
But import the v0.2.2 version, The result is as follows
```
[...{
        name: string
}]
```
and, This is what i expected

**Comment by myitcv** [comment] 2021-04-01 14:04
@leejanee - thanks for raising this.

Just as an FYI, there are some tips on how to create clean reproducers in https://github.com/cuelang/cue/wiki/Creating-test-or-performance-reproducers. The `txtar` format is particularly good when it comes to multi-file repros, as is the case here. 

For example, here is my reproducer based on the above:

```
exec go mod tidy
exec go run main.go
cmp stdout stdout.golden

-- go.mod --
module mod.com

go 1.16

require cuelang.org/go v0.3.0-beta.8
-- main.go --
package main

import (
 "fmt"

 "cuelang.org/go/cue"
 "cuelang.org/go/cue/format"
)

func main() {
 var src = `
t: {name: string}
output: [...t]
`
 var r cue.Runtime
 inst, _ := r.Compile("-", src)
 ct, _ := format.Node(inst.Value().Lookup("output").Syntax(cue.ResolveReferences(true)))
 fmt.Println(string(ct))
}
-- stdout.golden --
[...{
	name: string
}]
```

### What did you expect to see?

The test pass. 

### What did you see instead?

```
> exec go run main.go
[stdout]
[...t]
> cmp stdout stdout.golden
[diff -stdout +stdout.golden]
-[...t]
+[...{
+       name: string
+}]
```

Creating such repros makes it much easier to confirm the issue, and indeed prepare a fix (because we have code/an example that can largely be copy-pasted). 

That said, this does appear to be a regression compared to v0.2.2 (confirmed a problem at tip, 792da39a7835f963f8c2b43d7e55c8eb5a951822), bisected to 845df056ca4facf04a7a844238d3f3da0d4dbe99. Therefore I suspect this will be fixed after the planned v0.3.0 release.

**Comment by wonderflow** [comment] 2021-04-15 02:33
@mpvl Hi, any progress about this issue, we're really want to upgrade to 0.3 while this issue blocks our needs.

**Comment by myitcv** [comment] 2021-05-27 16:35
@wonderflow @leejanee - just to check, this remains a priority for you?

**Comment by wonderflow** [comment] 2021-05-28 02:45
@myitcv  yes, our project [KubeVela](https://kubevela.io/) highly relies on this feature, and we love to use CUE very much.

**Comment by wonderflow** [comment] 2021-05-28 02:48
Now we are still using version 0.2.2 because of this block https://github.com/oam-dev/kubevela/blob/master/go.mod#L6

And our users love to use the feature sets in CUE >= 0.3, so we also very hope to upgrade. But one of our feature relies on it.

**Comment by myitcv** [comment] 2021-05-28 04:11
Ok, thanks for the update @wonderflow

**Comment by myitcv** [comment] 2021-05-28 08:44
@wonderflow I've tentatively marked this for `v0.5.0`. 

On a related subject, I would be keen to understand if/how we can add KubeVela to our regression testing setup, [`unity`](https://github.com/cue-sh/unity). Would you be happy for me to email you offline to discuss further?

**Comment by myitcv** [comment] 2021-06-01 15:00
@wonderflow @leejanee - when we come to look at this it would be good to understand exactly what semantics you expect from `cue.ResolveReferences`. My understanding from the example above is that given a CUE `Instance`/`Value`, you want to resolve all references to their literal equivalents, whether from within the package or across a package boundary. Does that match your understanding?

**Comment by leejanee** [comment] 2021-06-02 06:39
> @wonderflow @leejanee - when we come to look at this it would be good to understand exactly what semantics you expect from `cue.ResolveReferences`. My understanding from the example above is that given a CUE `Instance`/`Value`, you want to resolve all references to their literal equivalents, whether from within the package or across a package boundary. Does that match your understanding?

Yes it is, I expect that the result returned by the Syntax(cue.All(),cue.ResolveReferences(true)) method can be recompiled

**Comment by cueckoo** [comment] 2021-07-03 13:08
This issue has been migrated to https://github.com/cue-lang/cue/issues/867.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.

**Closed by cueckoo** 2021-07-03 13:08 UTC
Labels: NeedsFix, Triage
